services:
  - type: web
    name: credit-calc
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn calc:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
